Add push flag to support pushing to registry directly
project-copacetic/copacetic pull request #294
Opened 2023-09-07 18:06 UTC by RealHarshThakur

This PR enables direct push to registry from buildkit:
```
copa patch -i docker.io/library/alpine:3.16.4 -r patch.json -p ttl.sh/alpinepatched:1h
```

Closes #293

2023-09-07 23:42 UTC, sozercan commented
I am wondering if we should align with buildx CLI here. Ideally, we don't want to break existing users so what I was thinking was to use `--tag` to accept `registy/repo:tag` and `--push` can be a bool. to remain backwards compat, we can parse if `--tag` includes `:` and `/`. If it includes both `:` and `/`, retag the entire image. If it doesn't include both `:` and `/`, only replace the tag.

`-i foo.io/repo/image:tag -t -patched` -> foo.io/repo/image:tag-patched (what we have today)
`-i foo.io/repo/image:tag -t bar.io/repo/image:tag` ->  bar.io/repo/image:tag
`-i foo.io/repo/image:tag -t bar.io/repo/image` -> invalid (must provide tag)
`-i foo.io/repo/image:tag -t repo/image:tag` -> invalid (must provide registry)

@jeremyrickard @cpuguy83 wdyt?

2023-09-08 00:12 UTC, jeremyrickard commented
> I am wondering if we should align with buildx CLI here. Ideally, we don't want to break existing users so what I was thinking was to use `--tag` to accept `registy/repo:tag` and `--push` can be a bool. to remain backwards compat, we can parse if `--tag` includes `:` and `/`. If it includes both `:` and `/`, retag the entire image. If it doesn't include both `:` and `/`, only replace the tag.
> 
> `-i foo.io/repo/image:tag -t -patched` -> foo.io/repo/image:tag-patched (what we have today) `-i foo.io/repo/image:tag -t bar.io/repo/image:tag` -> bar.io/repo/image:tag `-i foo.io/repo/image:tag -t bar.io/repo/image` -> invalid (must provide tag) `-i foo.io/repo/image:tag -t repo/image:tag` -> invalid (must provide registry)
> 
> @jeremyrickard @cpuguy83 wdyt?

I like the `-i foo.io/repo/image:tag -t bar.io/repo/image:tag` syntax. 

I also think that adding a --push flag would be useful, especially if it didn't require docker locally.  Not the same scenario, but the experience with`ko` and pushing images w/o docker is super useful.

2023-09-08 08:45 UTC, RealHarshThakur commented
cool, happy to go with what you folks suggested. 

Although, I am not sure about this bit:
```
-i foo.io/repo/image:tag -t repo/image:tag -> invalid (must provide registry)
```

This might still be what the user wants, partially due to how popular dockerhub is: `username/image:tag` is valid over there. Also, other such registries like `ttl.sh` also don't mind that format.

2023-09-08 09:42 UTC, RealHarshThakur commented
I've pushed a commit to get most of what you folks suggested. Added couple test cases that shows we'll be backwards-compatible and a new case for specifying a different registry. I've tried to stay unopinionated about destination registry conventions as copa will throw an error during push if buildkit fails to push anyway. Happy to take your suggestions tho

2023-09-08 09:48 UTC, RealHarshThakur commented
I think setting up the mock buildkit API  in unit tests failed, is it acting flaky?

2023-09-08 16:51 UTC, sozercan commented
> This might still be what the user wants, partially due to how popular dockerhub is: username/image:tag is valid over there. Also, other such registries like ttl.sh also don't mind that format.

this is being consistent with `-i` since you must provide `docker.io` there

2023-09-11 18:17 UTC, RealHarshThakur commented
> this is being consistent with -i since you must provide docker.io there

cool, I've added the registry check  @sozercan

2023-09-22 14:40 UTC, RealHarshThakur commented
@sozercan @jeremyrickard don't mean to badger, is there anything else you'd like me to change on this PR?

2023-09-22 14:59 UTC, salaxander commented
@RealHarshThakur sorry for the delay - @sozercan has been on vacation for the past couple days. I'll see if I can get you a review asap :)

2023-10-03 20:54 UTC, sozercan requested changes
Sorry about the delay! Please see comments

2023-10-03 20:54 UTC, sozercan commented on pkg/patch/patch_test.go
> +			patchedTag: "my.registry/nginx:1.21.3-patched",
this should be valid (something like `myregistry.azurecr.io/nginx:1.21.3-patched`)

2023-10-03 20:54 UTC, sozercan commented on pkg/patch/patch.go
> +			log.Error(err)
i think this is duplicate, since return is logged already?

2023-10-16 21:39 UTC, sozercan commented
ping @RealHarshThakur. we are getting close to cutting v0.5.0 release if you want this to be included

2023-10-17 11:55 UTC, RealHarshThakur commented
I'll try but most likely,  I'll be able to pick it up by end of the month

2023-11-09 19:54 UTC, RealHarshThakur commented
@sozercan  sorry for the delay, I've made the changes you've requested.

2024-07-03 18:43 UTC, sozercan commented
Closing due to inactivity. Please feel free to re-open if there's ongoing work. Thanks!

2024-07-03 18:43 UTC, closed without merging