test: increase code coverage
project-copacetic/copacetic pull request #704
Opened 2024-07-16 21:10 UTC by MiahaCybersec

Related to #40

2024-07-16 21:22 UTC, MiahaCybersec commented
The one failing test is due to mocks relying on `github.com/tonistiigi/fsutil/types`. This is required for the mocks to work. More specifically, this is required for mocking the behaviour of this line:

https://github.com/project-copacetic/copacetic/blob/9da12469013f43505f91afab625b8351b5644fe2/pkg/buildkit/buildkit.go#L88

2024-07-18 02:31 UTC, ashnamehrotra commented
@MiahaCybersec could you try running "go mod tidy"?

2024-08-02 22:55 UTC, ashnamehrotra commented on mocks/mock_gwclient.go
> +func (m *MockGWClient) ResolveSourceMetadata(ctx context.Context, op *pb.SourceOp, opt sourceresolver.Opt) (*sourceresolver.MetaResponse, error) {
I don't think we are calling this function?

2024-08-02 23:05 UTC, ashnamehrotra requested changes

2024-08-02 23:05 UTC, ashnamehrotra commented on pkg/buildkit/connhelpers/docker_test.go
> +			wantErr: false,
could we add a test case where we check for err?

2024-08-09 20:59 UTC, MiahaCybersec commented
Had to resolve some conflicts between my branch and main which forced a merge

2024-08-14 00:19 UTC, ashnamehrotra approved these changes
LGTM

2024-08-14 00:20 UTC, merged