Update go.mod changed go version from 1.22 to 1.23
project-copacetic/copacetic pull request #773
Opened 2024-09-15 18:46 UTC by ishwarmt

Describe the changes in this pull request using active verbs such as _Add_, _Remove_, _Replace_ ...

Closes #<_issue_ID_>

2024-09-17 16:48 UTC, ashnamehrotra commented
@ishwarmt running a go mod tidy may fix the dependency failure

2024-10-04 23:20 UTC, sozercan requested changes

2024-10-04 23:20 UTC, sozercan commented on go.mod
> +go 1.23.0
afaik this signals that 1.23 is the min version require to import this. copa isn't designed to be use as a library and not sure why would we want 1.23 as a min version?

2024-11-12 19:55 UTC, sozercan commented
closing this, feel free to re-open if there's a specific reason we want to bump go directive

2024-11-12 19:55 UTC, closed without merging