Update installation.md
project-copacetic/copacetic pull request #820
Opened 2024-11-02 21:09 UTC by pradhans0906

Prequisitives > Prerequisites

Describe the changes in this pull request using active verbs such as _Add_, _Remove_, _Replace_ ...

Closes #<_issue_ID_>

2024-11-04 14:17 UTC, ashnamehrotra commented
@pradhans0906 thank you for fixing this! Can we change this in all of the version docs?

2024-11-04 22:34 UTC, ashnamehrotra approved these changes

2024-11-04 22:34 UTC, ashnamehrotra requested changes
LGTM after DCO signoff fix

2024-11-04 23:08 UTC, sozercan approved these changes

2024-11-05 21:10 UTC, ashnamehrotra approved these changes

2024-11-05 21:10 UTC, merged